# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_webwallet', '0003_auto_20160115_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='extra_balance',
        ),
    ]
