# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_webwallet', '0004_remove_extra_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='change_wallet',
            new_name='internal_wallet',
        ),
    ]
