# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_webwallet', '0005_auto_20170611_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='incoming_txid',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('receiving_address', 'incoming_txid')]),
        ),
    ]
